# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7a8d01aa6e87f5b8a3cec947ca718f365db6dad50a6e95070a97b912bdebfb987adda117d79e8602e0ef3b9b9c70fba23f156a48fafb33450e7c616abf813f0

test:
  secret_key_base: afd828720e44e9b7df38f0f4d064d4307bac29833a030203e6241daf33b75081cf7ca79d7338b14260352528876caef23d9dd827807bbecebe994e1c3784664c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
